DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE (
  ID INT NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(255) NOT NULL DEFAULT '',
  LAST_NAME VARCHAR(255) NOT NULL DEFAULT '',
  TITLE VARCHAR(50) NOT NULL DEFAULT '',
  PHONE_NUMBER VARCHAR(255) NOT NULL,
  EMAIL VARCHAR (255) NOT NULL,
  HIRE_DATE DATE DEFAULT NULL,
  MANAGER_ID INT,
  DEPARTMENT_ID INT NOT NULL ,
  PRIMARY KEY (ID));

DROP TABLE DEPARTMENT;

CREATE TABLE DEPARTMENT (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR2(255) NOT NULL DEFAULT '',
  EMPLOYEE_ID INT NOT NULL DEFAULT '',
  PRIMARY KEY (ID)
);


DROP SEQUENCE hibernate_sequence;

CREATE SEQUENCE hibernate_sequence;